language: rust
rust:
  - 1.22.1
  - stable
  - nightly

script: cargo test --verbose --all

jobs:
  include:
    - stage: test
      script: bash -x ./tests/tests.sh
      rust: stable
    - stage: deploy
      rust: stable
      script: ./bin/build-docs.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: target/doc
        on:
          branch: master
