language: rust
rust:
  - stable
  - nightly
script:
  - cargo test --verbose --all
  - bash -x ./tests/tests.sh

jobs:
  include:
    - stage: deploy
      rust: stable
      script: ./bin/build-docs.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: target/doc
        on:
          branch: master
