[workspace]
members = [
    "src/strymon_communication",
    "src/strymon_runtime",
    "src/strymon_model",
    "src/strymon_rpc",
    "src/strymon_job",
    "apps/connected-components",
    "apps/topology-generator",
    #"apps/deltapath-routing",
]

[profile.release]
debug = true
