[package]
name = "fault-injection"
version = "0.2.0"
authors = ["Sebastian Wicki <swicki@inf.ethz.ch>"]

[dependencies.strymon_job]
path = "../../src/strymon_job"

[dependencies.topology_generator]
path = "../topology-generator"
