[package]
name = "connected_components"
version = "0.1.1"
authors = ["Sebastian Wicki <swicki@inf.ethz.ch>"]

[dependencies]
timely = "0.5"
differential-dataflow = "0.5"

[dependencies.strymon_job]
path = "../../src/strymon_job"

[dependencies.topology_generator]
path = "../topology-generator"
