[package]
authors = ["Sebastian Wicki <swicki@inf.ethz.ch>"]
name = "strymon_model"
version = "0.1.2"

[dependencies]
abomonation = "0.5.0"
abomonation_derive = "0.2.3"
serde = "1.0"
serde_derive = "1.0"
typename = "0.1"
