[package]
authors = ["Sebastian Wicki <swicki@inf.ethz.ch>"]
name = "strymon_communication"
version = "0.1.2"

[dependencies]
bytes = "0.4"
byteorder = "1.0"
serde = "1.0"
rmp-serde = "0.13"
futures = "0.1"
log = "0.4"
